sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - EXECUTE_CS_CHECK=true
    - php: 7.0
    - php: 7.1
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
 - phpenv config-rm xdebug.ini || return 0
 - composer self-update
 - cp tests/TestConfiguration.php.travis tests/TestConfiguration.php

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
 - ./vendor/bin/phpunit -c ./tests/
 - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi

notifications:
  irc: "irc.freenode.org#zftalk.dev"
  email: false
